name: Test workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build for Linux
      run: go build -v
    - name: Build for Windows
      run: GOOS=windows go build -v

    #- name: Test
    #  run: go test -v
